using Controls.ControlLibrary;
using Controls.Framework.Interfaces;
using System;
using System.Collections.Generic;
using System.Globalization;

namespace Controls.Framework
{
    public interface ISessionContext
    {
        /*Token Generated by the Platform/UI API which will be stored here.*/
        string SessionToken { get; }

        /*Identify the Device Type from the User Request*/
        GUIHost HostDevice { get; }

        /*List of User Permission*/
        object UserPermisssion { get; }

        /*List of User Tran Limit based on the Tran Code*/
        object UserTransactionLimit { get; }

        /*Stores the User Preferences*/
        IUserProfile UserProfile { get; }

        List<UILayoutConfig> LayoutConfig { get; }

        List<IUserTask> UserTask { get; set; }

        List<ISiteConfigSetting> SiteConfig { get;}

        string HostName { get; set; }

        string HostIP { get; set; }

        void SetSiteConfig(List<ISiteConfigSetting> configSettings);
    }
}
